export const SET_ALL_USERS = "SET_ALL_USERS";
export const OPEN_EDIT_USER_MODAL = "OPEN_EDIT_USER_MODAL";
export const SET_USER_TO_EDIT = "SET_USER_TO_EDIT";
export const UPDATE_USER_CALLBACK = "UPDATE_USER_CALLBACK";
