// users actions
export const SET_ALL_USERS = "SET_ALL_USERS";
export const OPEN_EDIT_USER_MODAL = "OPEN_EDIT_USER_MODAL";
export const SET_USER_TO_EDIT = "SET_USER_TO_EDIT";
export const UPDATE_USER_CALLBACK = "UPDATE_USER_CALLBACK";
export const DELETE_USER = "DELETE_USER";
export const CREATE_NEW_USER = "CREATE_NEW_USER";

// movies actions
export const SET_ALL_MOVIES_LIST = "SET_ALL_MOVIES_LIST";
export const LOAD_MORE_MOVIES = "LOAD_MORE_MOVIES";
export const OPEN_MOVIE_DETAILS_MODAL = "OPEN_MOVIE_DETAILS_MODAL";
export const SET_MOVIE_DETAILS = "SET_MOVIE_DETAILS";
export const SET_MOVIES_LENGTH = "SET_MOVIES_LENGTH";

// posts actions
export const SET_ALL_POSTS_LIST = "SET_ALL_POSTS_LIST";
export const CREATE_NEW_POST = "CREATE_NEW_POST";
export const DELETE_POST = "DELETE_POST";

// MAIN ACTIONS
export const SET_CURRENT_USER_DATA = "SET_CURRENT_USER_DATA";
export const OPEN_SELECT_USER_MODAL = "OPEN_SELECT_USER_MODAL";
export const ADD_NEW_COMMENT = "ADD_NEW_COMMENT";
export const OPEN_CREATE_POST_MODAL = "OPEN_CREATE_POST_MODAL";
export const OPEN_CREATE_FOLDER_MODAL = "OPEN_CREATE_FOLDER_MODAL";

// admin action
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const IS_ADMIN_LOGGED = "IS_ADMIN_LOGGED";

// links actions
export const GET_ALL_LINKS = "GET_ALL_LINKS";
export const CREATE_NEW_FODER = "CREATE_NEW_FODER";
